### ISSUE TITLE
Animation fixes soon?

### ISSUE THREAD

**Issue by AzureAxi** [M6FGR/DualSpears#1]
I've seen that you are kind of new to making epic fight mods i guess, but i think the animations should be enhanced a little more 
(the first attack should be two spears attacking aswell) as the 2nd attack followup, it is good enough but the 3rd one is just a 
skip in frames to just be able to do a jumping attack which looks unrealistic and ruins the fun. I hope you get better at animating so that more people could enjoy your work.

You may also need to rework the skill, as it would only hit once at the end of the skill making you vulnerable to attacks especially when there is a strong enemy around you.

I also noticed that the skill only hits once instead of twice during the spin, i thought it would hit two times but it seems that my expectations were very low for this mod. I hope you can do better than this one.

**Comment by dieeeeeeeego** [comment]
Thanks for the suggestion, currently at the moment im reworking all the animations and making them better as im not too good at epic fights blender model. also about the skill, im thinking about changing it into something else than the current one because im not satisfied yet with it

**Comment by AzureAxi** [comment]
You can probably make the dash attack into a double spear thrust without them overlapping. But i do not understand why is there only one hitbox on the right spear only but why not make a large hitbox covering both spears.

**Comment by dieeeeeeeego** [comment]
dw about that i worked on it, everything weird will be fixed in the next update soon

**Comment by AzureAxi** [comment]
Thanks, me and my friend are waiting for the update. He tried this mod first and told me to review it.
