### ISSUE TITLE
Update on your mod (another review)

### ISSUE THREAD

**Issue by AzureAxi** [M6FGR/DualSpears#2]
I have seen you have updated it, i have a few suggestions off the animations. The 3rd attack in the combo, the left spear is flying and not in the hand of the player.

![image_2024-08-03_181453308](https://github.com/user-attachments/assets/71fedb08-511f-4d79-a5c7-fe89c2e06422)

You may be able to fix this or not, it'd be a huge help to your mod if the players have liking to it.
The second fix you should be doing, the skill book itself, the description is very non-rpg like, and is incorrect.

![image](https://github.com/user-attachments/assets/3a97f1f6-215a-4f98-a888-6afea7a9d1f4)

As you can see, it says to hold 2 tachi's which is not a spear.
It's either you are bad at english or you were way too drunk (lol)
I have also seen that the skillbook says "20% more damage", in which i tested that it DOES not boost dmg.
Just replace the "20% more damage" with "Allows you to dual wield spears."

Last fix, the skill itself is called "Slash", which is weird. It should have a name probably like "Spear Takedown" or something.
Slash is to cut something with a sweeping movement, but i guess thats also called "Slashing" but that is a weird name for a rpg mod.

Suggestion - Make animations a bit faster to make it balanced, i tested this mod with Netherite armor vs the Ender dragon.
The weight of the netherite armor made the dual spears SO slow so it should be more faster.

:D

**Comment by AzureAxi** [comment]
oh wait actually the attack speed doesnt depend on the animation oops

**Comment by dieeeeeeeego** [comment]
The first one actually idk why it is flying 

in the animation blend it looks pretty good but imma take a guess and say that the spear ingame is smaller than the one in blender and ill take a look at that

**Comment by dieeeeeeeego** [comment]
The second one is a mistake that i did replaced the description for the skill

And im not bad at english

**Comment by dieeeeeeeego** [comment]
And about the 20% damage. Im so sure that i didnt put any damage boost or any additional perks. Only the skill

**Comment by dieeeeeeeego** [comment]
But thanks for letting me know ill work on it rn
